name: Docker build

on:
  # schedule:
  #   - cron: '0 0 * * 0' # weekly at 00:00 on Sunday -> https://crontab.guru/#0_0_*_*_0
  push:
    branches:
      - 'main'
    paths:
      - '**/*'
      - '!docs'
  workflow_dispatch:

env:
  repo_major_minor: '0.1'  # manually update for major.minor changes

jobs:
  set_build_counter:
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.set-build-counter.outputs.count }}
    steps:
      - uses: actions/checkout@v3
      - uses: mshafer1/gh-actions/set-build-counter@main
        id: set-build-counter
        with:
          seed: '${{ env.repo_major_minor }}'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} # default GITHUB_TOKEN has no permission to set repo variables, must be a PAT that has variable write
  build_and_push:
    runs-on: ubuntu-latest
    needs: set_build_counter
    strategy:
      matrix:
        app:
          - dnsmasq
          - envsubst
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}
          flavor: |
            latest=true
          lables: |
            org.opencontainers.image.description="Docker image for ${{ matrix.app }}"
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern=build-{{ env.repo_major_minor }}.{{ needs.set_build_counter.outputs.count }}
            type=semver,pattern=build-{{ env.repo_major_minor }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max # mode=max exports all layers for maximum caching
          push: false
          tags: ${{ steps.meta.outputs.tags }}
      - name: Tag with app version and conditionally push
        run: |
          app_version_command="$(cat ./${{ matrix.app }}/_get_version.sh)"
          echo Running version command: $app_version_command
          app_version=$(docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}:latest "${app_version_command}")
          major_app_version=`echo ${app_version} | cut -d'.' -f1`

          decider_version="build-${{ env.repo_major_minor }}_${{ matrix.app }}-${app_version}"

          if ! docker pull ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}:${decider_version}; then
            echo "Tagging with version ${app_version} and pushing"

            for v in ${{ matrix.app }}_${app_version} ${{ matrix.app }}_${major_app_version} ${decider_version}; do
              docker tag dev/${{ matrix.app }}:latest ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}:$v
            done

            docker image push --all-tags ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}
          else
            echo "Version ${app_version} already pushed"
          fi
